swagger: '2.0'
info:
  description: Identity Broker APIs
  version: "2.0.0"
  title: Simple Broker APIs
  # put the contact info for your development or API team
  contact:
    email: sonu.s@hpe.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: IdentityAdmin
  description: Identity and RBAC Operations.

paths:
  /providers:
    get:
      tags:
      - IdentityAdmin
      summary: searches inventory of Indentity Providers
      operationId: getListIdentityProviders
      description: |
        By passing in the appropriate options, you can search for
        available inventory of Identity providers in the system
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 10
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Provider'
        400:
          description: bad input parameter
    post:
      tags:
      - IdentityAdmin
      summary: Registers an existing identity system to OneSphere for lookups and managing SSO profiles for Users, Groups and Apps.
        Additionally, it configures OneSphere SSO profile in the
        Identity Provider
      operationId: registerNewProvider
      description: Registers a Provider to OneSphere
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: system
        description: Provider to add
        schema:
          $ref: '#/definitions/ProviderRegistrationOption'
      responses:
        201:
          description: Registered
          schema:
            $ref: '#/definitions/RegistrationStatus'
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
  /providers/{ProviderId}:
    get:
      tags:
      - IdentityAdmin
      summary: searches inventory of Indentity Providers
      operationId: getIdentityProviderById
      description: |
        By passing in the appropriate options, you can search for
        available inventory of Identity providers in the system
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 10
      - in: path
        name: ProviderId
        description: pass a provider-id for more detailed information on Identity provider
        required: true
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Provider'
        400:
          description: bad input parameter
    patch:
      tags:
      - IdentityAdmin
      summary: Updates connected identity system configuration in OneSphere
      operationId: updateProvider
      description: Updates an already configured Provider to OneSphere
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: ProviderId
        description: pass a provider-id to update
        required: true
        type: string
      - name: JsonPatch
        in: body
        required: true
        schema:
          $ref: "#/definitions/PatchRequest"
      responses:
        201:
          description: item updated
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
  /providers/{ProviderId}/{providerNamespace}/resources/{resourceType}/{resourceName}:
    get:
      tags:
      - IdentityAdmin
      summary: searches inventory of Users behind all configured Identity systems or based on the filter
      operationId: getManagedUsers
      description: |
        By passing in the appropriate filter options, you can search for
        Users available in the inventory managed by the Identity Provider.
      produces:
      - application/json
      parameters:
      - in: path
        name: ProviderId
        description: pass the provider-id to list the resources from
        required: true
        type: string
      - in: path
        name: providerNamespace
        description: pass an optional sub-unit in the provider to list the resources from. For e.g. OrganizationId in Okta
        required: true
        type: string
      - in: path
        name: resourceType
        description: choose a valid type of resource. For e.g. User, Group, Application etc.
        required: true
        type: string
      - in: path
        name: resourceName
        description: choose a valid name of and existing resource. For e.g. bob.marine if type is User.
        required: true
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Resource'
        400:
          description: bad input parameter
  /providers/{ProviderId}/{providerNamespace}/resources/types:
    get:
      tags:
      - IdentityAdmin
      summary: searches inventory of Users behind all configured Identity systems or based on the filter
      operationId: getSupportedResourceTypes
      description: |
        By passing in the appropriate filter options, you can search for
        Users available in the inventory managed by the Identity Provider.
      produces:
      - application/json
      parameters:
      - in: path
        name: ProviderId
        description: pass the provider-id to list the resource types from
        required: true
        type: string
      - in: path
        name: providerNamespace
        description: pass an optional sub-unit in the provider to list the resources types from. For e.g. OrganizationId in Okta
        required: true
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/ResourceType'
        400:
          description: bad input parameter
  /providers/{ProviderId}/{providerNamespace}/resources/bindings:
    post:
      tags:
      - IdentityAdmin
      summary: Binds resources to each other. For e.g. Assigning a User to the Application in Okta.
      operationId: createResourceBinding
      description: Creates a new assignment in the Provider between resources.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: ProviderId
        description: pass the provider-id to bind the resources
        required: true
        type: string
      - in: path
        name: providerNamespace
        description: pass an optional sub-unit in the provider to list the resources from. For e.g. OrganizationId in Okta
        required: true
        type: string      
      - in: body
        name: bindings
        description: Resource or Container to modify
        schema:
         type: array
         items:
           $ref: '#/definitions/ResourceBindingOption'
      responses:
        201:
          description: Binding created for Scope
          schema:
            $ref: '#/definitions/ResourceBinding'
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists  
  /providers/{ProviderId}/{providerNamespace}/resources/bindings/{resourceType}/{resourceName}:
    get:
      tags:
      - IdentityAdmin
      summary: Returns binding information of a resource.
      operationId: ListResourceBindingInfo
      description: List all resource binding information for the given resource.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: ProviderId
        description: pass the provider-id to bind the resources
        required: true
        type: string
      - in: path
        name: providerNamespace
        description: pass an optional sub-unit in the provider to list the resources from. For e.g. OrganizationId in Okta
        required: true
        type: string
      - in: path
        name: resourceType
        description: Valid resource type in the system
        required: true
        type: string
      - in: path
        name: resourceName
        description: Valid resource name available in the system
        required: true
        type: string
      responses:
        200:
          description: List binding information
          schema:
           type: array
           items:
             $ref: '#/definitions/ResourceBinding'
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
  /providers/{ProviderId}/{providerNamespace}/resources/{resourceType}/{resourceName}/sso:
    post:
      tags:
      - IdentityAdmin
      summary: Configures SSO profile for a resource in the Identity Provider.
      operationId: createSSOProfile
      description: Creates new SSO profile for resources in the Identity provider.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: ProviderId
        description: pass the provider-id to bind the resources
        required: true
        type: string
      - in: path
        name: providerNamespace
        description: pass an optional sub-unit in the provider to list the resources from. For e.g. OrganizationId in Okta
        required: true
        type: string
      - in: path
        name: resourceType
        description: Valid resource type in the system
        required: true
        type: string
      - in: path
        name: resourceName
        description: Valid resource name available in the system
        required: true
        type: string
      - in: body
        name: ssoprofile
        description: sso profile
        schema:
           $ref: '#/definitions/ResourceSSOProfile'
      responses:
        201:
          description: SSO profile for a resource
          schema:
            $ref: '#/definitions/ResourceSSOProfile'
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists    
definitions:
  Resource:
    type: object
    required:
    - id
    - name
    - kind
    - managedBy
    - plans
    - tags
    - state
    - properties
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: 101-Dalmations
      kind:
        type: string
        example: User | Group | Application
      managedBy:
        type: string
        example: OneShpere, System
      tags:
       $ref: '#/definitions/Tags'
      state:
        type: boolean
        example: true
      properties:
        $ref: '#/definitions/Attributes'
  Attributes:
    type: object
    properties:
      Key:
        type: string
        example: OKTA_OAUTH2.0_METADATA
      Value:
        type: string
        example: http://dev-2019.oktapreview.com/oAuth2.0/default
  Tags:
    type: object
    description: A list of values
    required:
      - values
    properties:
      values:
        type: array
        items:
            type: string
  APICredentials:
    properties:
      accessKeyID:
        type: string
        example: 408-867-5309
      accessSecret:
        type: string
        example: 408-867-5309
      cert:
        type: string
        example: ""
  ResourceSSOProfile:
    properties:
     ssoUrl: 
      type: string
     attributes:
      type: array
      items:
        $ref: '#/definitions/Attributes'
  AppSSOCredentials:
    properties:
      clientId:
        type: string
        example: 408-867-5309
      clientSecret:
        type: string
        example: 408-867-5309
  Provider:
    required:
    - name
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
        example: hpe-2019.oktapreview.com
      namespace:
        type: string
        example: organization1
      authUrl:
        type: string
        format: url
        example: "https://okta-preview-dev2019.com/"
      state:
        type: string
        enum:
        - "enabled"
        - "error"
        - "disabled"
      properties:
        type: array
        items:
          $ref: '#/definitions/Attributes'
  ProviderRegistrationOption:
    required:
    - namespace
    - creds
    - url
    properties:
      name:
        type: string
        example: friendly-name
      namespace:
        type: string
        example: organization1
      authUrl:
        type: string
        format: url
        example: "https://okta-preview-dev2019.com/"
      creds:
        $ref: '#/definitions/APICredentials'
  RegistrationStatus:
    required:
    - error
    - originalError
    - description
    - providerUrl
    properties:
      error:
        type: boolean
      description:
        type: string
        example: Cert failed
      originalError:
        type: string
        example: Communication reset by peer.
      providerUrl:
        type: string
        format: url
        example: "https://okta-preview-dev2019.com/"
  ResourceType:
    required:
    - name
    - pathPrefix
    properties:
      name:
        type: string
      pathPrefix:
        type: string
        example: providers/resources/user
  ResourceRef:
   required:
   - Id
   - url
   - kind
   properties:
    Id:
     type: string
     format: uuid
    url:
     type: string
     format: url
    kind:
     type: string
     example: "User or Group or Application or any other resource type supported by the System"
  ResourceBindingOption:
   required:
   - scope
   - subject
   - tags
   properties:
     scope:
        $ref: '#/definitions/ResourceRef'
     subject:
        $ref: '#/definitions/ResourceRef'
     tags:
        $ref: '#/definitions/Tags'
  ResourceBinding:
   required:
   - scope
   - bindings
   properties:
     scope:
        $ref: '#/definitions/ResourceRef'
     bindings:
      type: array
      items:
       $ref: '#/definitions/ResourceRef'
  PatchRequest:
    type: array
    items:
      $ref: "#/definitions/PatchDocument"
  PatchDocument: 
    description: A JSONPatch document as defined by RFC 6902 
    required:
     - "op"
     - "path"
    properties: 
     op: 
      type: string 
      description: The operation to be performed 
      enum:
       - "add"
       - "remove"
       - "replace"
     path: 
      type: string 
      description: A JSON-Pointer 
     value: 
      type: object 
      description: The value to be used within the operations.
     from: 
      type: string 
      description: A string containing a JSON Pointer value.
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /rest/identity/v1/
schemes:
 - https
# Added by API Auto Mocking Plugin
# basePath: /rest/identity/v1
# Added by API Auto Mocking Plugin
# basePath: /rest/identity/v1
# Added by API Auto Mocking Plugin
basePath: /sudhakso/IdentityBroker/1.0.0
