// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Resource_ResourceIdType int32

const (
	Resource_ONESPHERE_OWNED   Resource_ResourceIdType = 0
	Resource_ONESPHERE_MANAGED Resource_ResourceIdType = 1
	Resource_SYSTEM_MANAGED    Resource_ResourceIdType = 2
)

var Resource_ResourceIdType_name = map[int32]string{
	0: "ONESPHERE_OWNED",
	1: "ONESPHERE_MANAGED",
	2: "SYSTEM_MANAGED",
}

var Resource_ResourceIdType_value = map[string]int32{
	"ONESPHERE_OWNED":   0,
	"ONESPHERE_MANAGED": 1,
	"SYSTEM_MANAGED":    2,
}

func (x Resource_ResourceIdType) String() string {
	return proto.EnumName(Resource_ResourceIdType_name, int32(x))
}

func (Resource_ResourceIdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{4, 0}
}

type ProviderOpts struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace            []string `protobuf:"bytes,2,rep,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderOpts) Reset()         { *m = ProviderOpts{} }
func (m *ProviderOpts) String() string { return proto.CompactTextString(m) }
func (*ProviderOpts) ProtoMessage()    {}
func (*ProviderOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{0}
}

func (m *ProviderOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderOpts.Unmarshal(m, b)
}
func (m *ProviderOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderOpts.Marshal(b, m, deterministic)
}
func (m *ProviderOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderOpts.Merge(m, src)
}
func (m *ProviderOpts) XXX_Size() int {
	return xxx_messageInfo_ProviderOpts.Size(m)
}
func (m *ProviderOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderOpts.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderOpts proto.InternalMessageInfo

func (m *ProviderOpts) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProviderOpts) GetNamespace() []string {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type ResourceType struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PathPrefix           string   `protobuf:"bytes,3,opt,name=pathPrefix,proto3" json:"pathPrefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceType) Reset()         { *m = ResourceType{} }
func (m *ResourceType) String() string { return proto.CompactTextString(m) }
func (*ResourceType) ProtoMessage()    {}
func (*ResourceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{1}
}

func (m *ResourceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceType.Unmarshal(m, b)
}
func (m *ResourceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceType.Marshal(b, m, deterministic)
}
func (m *ResourceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceType.Merge(m, src)
}
func (m *ResourceType) XXX_Size() int {
	return xxx_messageInfo_ResourceType.Size(m)
}
func (m *ResourceType) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceType.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceType proto.InternalMessageInfo

func (m *ResourceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceType) GetPathPrefix() string {
	if m != nil {
		return m.PathPrefix
	}
	return ""
}

type ResourceTypes struct {
	Types                []*ResourceType `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResourceTypes) Reset()         { *m = ResourceTypes{} }
func (m *ResourceTypes) String() string { return proto.CompactTextString(m) }
func (*ResourceTypes) ProtoMessage()    {}
func (*ResourceTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{2}
}

func (m *ResourceTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTypes.Unmarshal(m, b)
}
func (m *ResourceTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTypes.Marshal(b, m, deterministic)
}
func (m *ResourceTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTypes.Merge(m, src)
}
func (m *ResourceTypes) XXX_Size() int {
	return xxx_messageInfo_ResourceTypes.Size(m)
}
func (m *ResourceTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTypes.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTypes proto.InternalMessageInfo

func (m *ResourceTypes) GetTypes() []*ResourceType {
	if m != nil {
		return m.Types
	}
	return nil
}

type ResourceKey struct {
	KeyName              string   `protobuf:"bytes,1,opt,name=keyName,proto3" json:"keyName,omitempty"`
	RegExp               string   `protobuf:"bytes,2,opt,name=regExp,proto3" json:"regExp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceKey) Reset()         { *m = ResourceKey{} }
func (m *ResourceKey) String() string { return proto.CompactTextString(m) }
func (*ResourceKey) ProtoMessage()    {}
func (*ResourceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{3}
}

func (m *ResourceKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceKey.Unmarshal(m, b)
}
func (m *ResourceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceKey.Marshal(b, m, deterministic)
}
func (m *ResourceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceKey.Merge(m, src)
}
func (m *ResourceKey) XXX_Size() int {
	return xxx_messageInfo_ResourceKey.Size(m)
}
func (m *ResourceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceKey.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceKey proto.InternalMessageInfo

func (m *ResourceKey) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func (m *ResourceKey) GetRegExp() string {
	if m != nil {
		return m.RegExp
	}
	return ""
}

type Resource struct {
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                 string                  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnType              Resource_ResourceIdType `protobuf:"varint,4,opt,name=ownType,proto3,enum=api.Resource_ResourceIdType" json:"ownType,omitempty"`
	Plan                 *ResourcePlan           `protobuf:"bytes,5,opt,name=plan,proto3" json:"plan,omitempty"`
	Tags                 []string                `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Properties           map[string]string       `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{4}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetOwnType() Resource_ResourceIdType {
	if m != nil {
		return m.OwnType
	}
	return Resource_ONESPHERE_OWNED
}

func (m *Resource) GetPlan() *ResourcePlan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *Resource) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Resource) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Resources struct {
	Resources            []*Resource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{5}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ResourcePlan struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiVersion           string   `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcePlan) Reset()         { *m = ResourcePlan{} }
func (m *ResourcePlan) String() string { return proto.CompactTextString(m) }
func (*ResourcePlan) ProtoMessage()    {}
func (*ResourcePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{6}
}

func (m *ResourcePlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcePlan.Unmarshal(m, b)
}
func (m *ResourcePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcePlan.Marshal(b, m, deterministic)
}
func (m *ResourcePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcePlan.Merge(m, src)
}
func (m *ResourcePlan) XXX_Size() int {
	return xxx_messageInfo_ResourcePlan.Size(m)
}
func (m *ResourcePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcePlan.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcePlan proto.InternalMessageInfo

func (m *ResourcePlan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourcePlan) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

type GetResourceOpts struct {
	Key                  *ResourceKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type                 *ResourceType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Provider             *ProviderOpts `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetResourceOpts) Reset()         { *m = GetResourceOpts{} }
func (m *GetResourceOpts) String() string { return proto.CompactTextString(m) }
func (*GetResourceOpts) ProtoMessage()    {}
func (*GetResourceOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{7}
}

func (m *GetResourceOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceOpts.Unmarshal(m, b)
}
func (m *GetResourceOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceOpts.Marshal(b, m, deterministic)
}
func (m *GetResourceOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceOpts.Merge(m, src)
}
func (m *GetResourceOpts) XXX_Size() int {
	return xxx_messageInfo_GetResourceOpts.Size(m)
}
func (m *GetResourceOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceOpts.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceOpts proto.InternalMessageInfo

func (m *GetResourceOpts) GetKey() *ResourceKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetResourceOpts) GetType() *ResourceType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *GetResourceOpts) GetProvider() *ProviderOpts {
	if m != nil {
		return m.Provider
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Resource_ResourceIdType", Resource_ResourceIdType_name, Resource_ResourceIdType_value)
	proto.RegisterType((*ProviderOpts)(nil), "api.ProviderOpts")
	proto.RegisterType((*ResourceType)(nil), "api.ResourceType")
	proto.RegisterType((*ResourceTypes)(nil), "api.ResourceTypes")
	proto.RegisterType((*ResourceKey)(nil), "api.ResourceKey")
	proto.RegisterType((*Resource)(nil), "api.Resource")
	proto.RegisterMapType((map[string]string)(nil), "api.Resource.PropertiesEntry")
	proto.RegisterType((*Resources)(nil), "api.Resources")
	proto.RegisterType((*ResourcePlan)(nil), "api.ResourcePlan")
	proto.RegisterType((*GetResourceOpts)(nil), "api.GetResourceOpts")
}

func init() { proto.RegisterFile("resource.proto", fileDescriptor_d1b72f771c35e3b8) }

var fileDescriptor_d1b72f771c35e3b8 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x6f, 0xd3, 0x40,
	0x0c, 0x6e, 0x92, 0xae, 0x5d, 0xdd, 0x2e, 0xcd, 0xcc, 0x40, 0x51, 0x35, 0x50, 0x75, 0xd2, 0x44,
	0x25, 0x44, 0x1f, 0x0a, 0x9a, 0x2a, 0xd0, 0x04, 0x43, 0x8b, 0x06, 0x1a, 0x6b, 0xa3, 0x74, 0x02,
	0xf1, 0x84, 0xc2, 0x7a, 0x8c, 0x53, 0x4b, 0x72, 0xba, 0xcb, 0xc6, 0xf2, 0x03, 0x78, 0xe2, 0x37,
	0xf1, 0xdf, 0x50, 0xae, 0x97, 0x34, 0x59, 0x27, 0xf1, 0xe6, 0xf8, 0xb3, 0x3f, 0xfb, 0xf3, 0xd9,
	0x01, 0x5b, 0x50, 0x19, 0x5f, 0x8b, 0x4b, 0x3a, 0xe4, 0x22, 0x4e, 0x62, 0xb4, 0x42, 0xce, 0xc8,
	0x5b, 0xe8, 0xf8, 0x22, 0xbe, 0x61, 0x73, 0x2a, 0xa6, 0x3c, 0x91, 0x88, 0x50, 0x4f, 0x52, 0x4e,
	0x5d, 0xa3, 0x6f, 0x0c, 0x5a, 0x81, 0xb2, 0x71, 0x1f, 0x5a, 0x51, 0xf8, 0x93, 0x4a, 0x1e, 0x5e,
	0x52, 0xd7, 0xec, 0x5b, 0x83, 0x56, 0xb0, 0x76, 0x90, 0x77, 0xd0, 0x09, 0x34, 0xf1, 0x45, 0x16,
	0x8d, 0x50, 0xcf, 0xc0, 0x9c, 0x21, 0xb3, 0xf1, 0x09, 0x00, 0x0f, 0x93, 0x1f, 0xbe, 0xa0, 0xdf,
	0xd9, 0xad, 0x6b, 0x29, 0xa4, 0xe4, 0x21, 0x63, 0xd8, 0x29, 0x73, 0x48, 0x7c, 0x0a, 0x5b, 0x59,
	0x69, 0xe9, 0x1a, 0x7d, 0x6b, 0xd0, 0x1e, 0xed, 0x0e, 0x43, 0xce, 0x86, 0xe5, 0x90, 0x60, 0x85,
	0x93, 0x37, 0xd0, 0xce, 0xdd, 0x67, 0x34, 0x45, 0x17, 0x9a, 0x0b, 0x9a, 0x4e, 0xd6, 0xf5, 0xf3,
	0x4f, 0x7c, 0x04, 0x0d, 0x41, 0xaf, 0xbc, 0x5b, 0xee, 0x9a, 0x0a, 0xd0, 0x5f, 0xe4, 0xb7, 0x05,
	0xdb, 0x39, 0x03, 0xda, 0x60, 0xb2, 0xb9, 0xce, 0x34, 0xd9, 0x3c, 0xd3, 0xb2, 0x60, 0xd1, 0x5c,
	0xa7, 0x28, 0xbb, 0xd0, 0x67, 0x95, 0xf4, 0x1d, 0x42, 0x33, 0xfe, 0x15, 0x65, 0x7d, 0xb9, 0xf5,
	0xbe, 0x31, 0xb0, 0x47, 0xfb, 0x95, 0x86, 0x0b, 0xe3, 0xc3, 0x5c, 0xf5, 0x9e, 0x07, 0xe3, 0x01,
	0xd4, 0xf9, 0x32, 0x8c, 0xdc, 0xad, 0xbe, 0xb1, 0xa1, 0xd2, 0x5f, 0x86, 0x51, 0xa0, 0x60, 0xf5,
	0x28, 0xe1, 0x95, 0x74, 0x1b, 0x6a, 0xf6, 0xca, 0xc6, 0x23, 0x00, 0x2e, 0x62, 0x4e, 0x45, 0xc2,
	0xa8, 0x74, 0x9b, 0x6a, 0x4c, 0x8f, 0xab, 0x55, 0xfd, 0x02, 0xf7, 0xa2, 0x44, 0xa4, 0x41, 0x29,
	0xa1, 0x77, 0x04, 0xdd, 0x3b, 0x30, 0x3a, 0x60, 0x2d, 0x68, 0xaa, 0xd5, 0x67, 0x26, 0xee, 0xc1,
	0xd6, 0x4d, 0xb8, 0xbc, 0xa6, 0x5a, 0xff, 0xea, 0xe3, 0x95, 0x39, 0x36, 0x88, 0x0f, 0x76, 0x55,
	0x13, 0x3e, 0x80, 0xee, 0x74, 0xe2, 0xcd, 0xfc, 0xf7, 0x5e, 0xe0, 0x7d, 0x9d, 0x7e, 0x9e, 0x78,
	0x27, 0x4e, 0x0d, 0x1f, 0xc2, 0xee, 0xda, 0x79, 0x7e, 0x3c, 0x39, 0x3e, 0xf5, 0x4e, 0x1c, 0x03,
	0x11, 0xec, 0xd9, 0x97, 0xd9, 0x85, 0x77, 0x5e, 0xf8, 0x4c, 0x32, 0x86, 0x56, 0xce, 0x28, 0xf1,
	0x19, 0xb4, 0xf2, 0x65, 0xcd, 0x57, 0x60, 0xa7, 0xa2, 0x2d, 0x58, 0xe3, 0xe5, 0x05, 0xf4, 0xf5,
	0xb4, 0xee, 0x5b, 0xc0, 0x90, 0xb3, 0x4f, 0x54, 0x48, 0x16, 0x47, 0x5a, 0x4e, 0xc9, 0x43, 0xfe,
	0x18, 0xd0, 0x3d, 0xa5, 0x49, 0xce, 0xa3, 0x4e, 0x81, 0xac, 0xe7, 0xd1, 0x1e, 0x39, 0x95, 0xf2,
	0x67, 0x34, 0x5d, 0x4d, 0xe8, 0x40, 0x9f, 0x8b, 0x79, 0xcf, 0x03, 0xaa, 0xa7, 0x5e, 0x5d, 0xd0,
	0x73, 0xd8, 0xe6, 0xfa, 0xca, 0xd4, 0xde, 0xe4, 0xa1, 0xe5, 0xd3, 0x0b, 0x8a, 0x90, 0xd1, 0x5f,
	0x03, 0x9c, 0x42, 0x92, 0x76, 0xe2, 0x4b, 0x68, 0x97, 0x3a, 0xc4, 0x3d, 0x45, 0x70, 0xa7, 0xe7,
	0x5e, 0x75, 0x4a, 0xa4, 0x86, 0x87, 0xd0, 0xf9, 0xc8, 0xe4, 0xff, 0xd2, 0xec, 0x4a, 0x9a, 0x24,
	0x35, 0x7c, 0x0d, 0x4e, 0x29, 0x68, 0x75, 0x94, 0x9b, 0x3d, 0xf7, 0x70, 0x43, 0xb1, 0x24, 0xb5,
	0x6f, 0x0d, 0xf5, 0x83, 0x79, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xbf, 0x44, 0x3f, 0x72,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceProviderClient is the client API for ResourceProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceProviderClient interface {
	GetResource(ctx context.Context, in *GetResourceOpts, opts ...grpc.CallOption) (*Resource, error)
	ListResource(ctx context.Context, in *GetResourceOpts, opts ...grpc.CallOption) (*Resources, error)
	GetResourceTypes(ctx context.Context, in *ProviderOpts, opts ...grpc.CallOption) (*ResourceTypes, error)
}

type resourceProviderClient struct {
	cc *grpc.ClientConn
}

func NewResourceProviderClient(cc *grpc.ClientConn) ResourceProviderClient {
	return &resourceProviderClient{cc}
}

func (c *resourceProviderClient) GetResource(ctx context.Context, in *GetResourceOpts, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := c.cc.Invoke(ctx, "/api.ResourceProvider/GetResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceProviderClient) ListResource(ctx context.Context, in *GetResourceOpts, opts ...grpc.CallOption) (*Resources, error) {
	out := new(Resources)
	err := c.cc.Invoke(ctx, "/api.ResourceProvider/ListResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceProviderClient) GetResourceTypes(ctx context.Context, in *ProviderOpts, opts ...grpc.CallOption) (*ResourceTypes, error) {
	out := new(ResourceTypes)
	err := c.cc.Invoke(ctx, "/api.ResourceProvider/GetResourceTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceProviderServer is the server API for ResourceProvider service.
type ResourceProviderServer interface {
	GetResource(context.Context, *GetResourceOpts) (*Resource, error)
	ListResource(context.Context, *GetResourceOpts) (*Resources, error)
	GetResourceTypes(context.Context, *ProviderOpts) (*ResourceTypes, error)
}

func RegisterResourceProviderServer(s *grpc.Server, srv ResourceProviderServer) {
	s.RegisterService(&_ResourceProvider_serviceDesc, srv)
}

func _ResourceProvider_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceProviderServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ResourceProvider/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceProviderServer).GetResource(ctx, req.(*GetResourceOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceProvider_ListResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceProviderServer).ListResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ResourceProvider/ListResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceProviderServer).ListResource(ctx, req.(*GetResourceOpts))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceProvider_GetResourceTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderOpts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceProviderServer).GetResourceTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ResourceProvider/GetResourceTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceProviderServer).GetResourceTypes(ctx, req.(*ProviderOpts))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ResourceProvider",
	HandlerType: (*ResourceProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResource",
			Handler:    _ResourceProvider_GetResource_Handler,
		},
		{
			MethodName: "ListResource",
			Handler:    _ResourceProvider_ListResource_Handler,
		},
		{
			MethodName: "GetResourceTypes",
			Handler:    _ResourceProvider_GetResourceTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource.proto",
}
