// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Resource_ResourceIdType int32

const (
	Resource_ONESPHERE_OWNED   Resource_ResourceIdType = 0
	Resource_ONESPHERE_MANAGED Resource_ResourceIdType = 1
	Resource_SYSTEM_MANAGED    Resource_ResourceIdType = 2
)

var Resource_ResourceIdType_name = map[int32]string{
	0: "ONESPHERE_OWNED",
	1: "ONESPHERE_MANAGED",
	2: "SYSTEM_MANAGED",
}

var Resource_ResourceIdType_value = map[string]int32{
	"ONESPHERE_OWNED":   0,
	"ONESPHERE_MANAGED": 1,
	"SYSTEM_MANAGED":    2,
}

func (x Resource_ResourceIdType) String() string {
	return proto.EnumName(Resource_ResourceIdType_name, int32(x))
}

func (Resource_ResourceIdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{4, 0}
}

type ProviderOpts struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProviderId           string   `protobuf:"bytes,3,opt,name=providerId,proto3" json:"providerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderOpts) Reset()         { *m = ProviderOpts{} }
func (m *ProviderOpts) String() string { return proto.CompactTextString(m) }
func (*ProviderOpts) ProtoMessage()    {}
func (*ProviderOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{0}
}

func (m *ProviderOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderOpts.Unmarshal(m, b)
}
func (m *ProviderOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderOpts.Marshal(b, m, deterministic)
}
func (m *ProviderOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderOpts.Merge(m, src)
}
func (m *ProviderOpts) XXX_Size() int {
	return xxx_messageInfo_ProviderOpts.Size(m)
}
func (m *ProviderOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderOpts.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderOpts proto.InternalMessageInfo

func (m *ProviderOpts) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProviderOpts) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ProviderOpts) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

type ResourceType struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PathPrefix           string   `protobuf:"bytes,3,opt,name=pathPrefix,proto3" json:"pathPrefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceType) Reset()         { *m = ResourceType{} }
func (m *ResourceType) String() string { return proto.CompactTextString(m) }
func (*ResourceType) ProtoMessage()    {}
func (*ResourceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{1}
}

func (m *ResourceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceType.Unmarshal(m, b)
}
func (m *ResourceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceType.Marshal(b, m, deterministic)
}
func (m *ResourceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceType.Merge(m, src)
}
func (m *ResourceType) XXX_Size() int {
	return xxx_messageInfo_ResourceType.Size(m)
}
func (m *ResourceType) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceType.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceType proto.InternalMessageInfo

func (m *ResourceType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceType) GetPathPrefix() string {
	if m != nil {
		return m.PathPrefix
	}
	return ""
}

type ResourceTypes struct {
	Types                []*ResourceType `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResourceTypes) Reset()         { *m = ResourceTypes{} }
func (m *ResourceTypes) String() string { return proto.CompactTextString(m) }
func (*ResourceTypes) ProtoMessage()    {}
func (*ResourceTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{2}
}

func (m *ResourceTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTypes.Unmarshal(m, b)
}
func (m *ResourceTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTypes.Marshal(b, m, deterministic)
}
func (m *ResourceTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTypes.Merge(m, src)
}
func (m *ResourceTypes) XXX_Size() int {
	return xxx_messageInfo_ResourceTypes.Size(m)
}
func (m *ResourceTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTypes.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTypes proto.InternalMessageInfo

func (m *ResourceTypes) GetTypes() []*ResourceType {
	if m != nil {
		return m.Types
	}
	return nil
}

type ResourceKey struct {
	KeyName              string   `protobuf:"bytes,1,opt,name=keyName,proto3" json:"keyName,omitempty"`
	RegExp               string   `protobuf:"bytes,2,opt,name=regExp,proto3" json:"regExp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceKey) Reset()         { *m = ResourceKey{} }
func (m *ResourceKey) String() string { return proto.CompactTextString(m) }
func (*ResourceKey) ProtoMessage()    {}
func (*ResourceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{3}
}

func (m *ResourceKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceKey.Unmarshal(m, b)
}
func (m *ResourceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceKey.Marshal(b, m, deterministic)
}
func (m *ResourceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceKey.Merge(m, src)
}
func (m *ResourceKey) XXX_Size() int {
	return xxx_messageInfo_ResourceKey.Size(m)
}
func (m *ResourceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceKey.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceKey proto.InternalMessageInfo

func (m *ResourceKey) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func (m *ResourceKey) GetRegExp() string {
	if m != nil {
		return m.RegExp
	}
	return ""
}

type Resource struct {
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                 string                  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnType              Resource_ResourceIdType `protobuf:"varint,4,opt,name=ownType,proto3,enum=api.Resource_ResourceIdType" json:"ownType,omitempty"`
	Plan                 *ResourcePlan           `protobuf:"bytes,5,opt,name=plan,proto3" json:"plan,omitempty"`
	Tags                 []string                `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Properties           map[string]string       `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{4}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetOwnType() Resource_ResourceIdType {
	if m != nil {
		return m.OwnType
	}
	return Resource_ONESPHERE_OWNED
}

func (m *Resource) GetPlan() *ResourcePlan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *Resource) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Resource) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Resources struct {
	Resources            []*Resource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{5}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ResourcePlan struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiVersion           string   `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourcePlan) Reset()         { *m = ResourcePlan{} }
func (m *ResourcePlan) String() string { return proto.CompactTextString(m) }
func (*ResourcePlan) ProtoMessage()    {}
func (*ResourcePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{6}
}

func (m *ResourcePlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcePlan.Unmarshal(m, b)
}
func (m *ResourcePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcePlan.Marshal(b, m, deterministic)
}
func (m *ResourcePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcePlan.Merge(m, src)
}
func (m *ResourcePlan) XXX_Size() int {
	return xxx_messageInfo_ResourcePlan.Size(m)
}
func (m *ResourcePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcePlan.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcePlan proto.InternalMessageInfo

func (m *ResourcePlan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourcePlan) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

type GetResourceOpts struct {
	Key                  *ResourceKey  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type                 *ResourceType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Provider             *ProviderOpts `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetResourceOpts) Reset()         { *m = GetResourceOpts{} }
func (m *GetResourceOpts) String() string { return proto.CompactTextString(m) }
func (*GetResourceOpts) ProtoMessage()    {}
func (*GetResourceOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{7}
}

func (m *GetResourceOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceOpts.Unmarshal(m, b)
}
func (m *GetResourceOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceOpts.Marshal(b, m, deterministic)
}
func (m *GetResourceOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceOpts.Merge(m, src)
}
func (m *GetResourceOpts) XXX_Size() int {
	return xxx_messageInfo_GetResourceOpts.Size(m)
}
func (m *GetResourceOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceOpts.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceOpts proto.InternalMessageInfo

func (m *GetResourceOpts) GetKey() *ResourceKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetResourceOpts) GetType() *ResourceType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *GetResourceOpts) GetProvider() *ProviderOpts {
	if m != nil {
		return m.Provider
	}
	return nil
}

type GetResourceTypeOpts struct {
	Type                 *ResourceType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Provider             *ProviderOpts `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetResourceTypeOpts) Reset()         { *m = GetResourceTypeOpts{} }
func (m *GetResourceTypeOpts) String() string { return proto.CompactTextString(m) }
func (*GetResourceTypeOpts) ProtoMessage()    {}
func (*GetResourceTypeOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{8}
}

func (m *GetResourceTypeOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceTypeOpts.Unmarshal(m, b)
}
func (m *GetResourceTypeOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceTypeOpts.Marshal(b, m, deterministic)
}
func (m *GetResourceTypeOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceTypeOpts.Merge(m, src)
}
func (m *GetResourceTypeOpts) XXX_Size() int {
	return xxx_messageInfo_GetResourceTypeOpts.Size(m)
}
func (m *GetResourceTypeOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceTypeOpts.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceTypeOpts proto.InternalMessageInfo

func (m *GetResourceTypeOpts) GetType() *ResourceType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *GetResourceTypeOpts) GetProvider() *ProviderOpts {
	if m != nil {
		return m.Provider
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Resource_ResourceIdType", Resource_ResourceIdType_name, Resource_ResourceIdType_value)
	proto.RegisterType((*ProviderOpts)(nil), "api.ProviderOpts")
	proto.RegisterType((*ResourceType)(nil), "api.ResourceType")
	proto.RegisterType((*ResourceTypes)(nil), "api.ResourceTypes")
	proto.RegisterType((*ResourceKey)(nil), "api.ResourceKey")
	proto.RegisterType((*Resource)(nil), "api.Resource")
	proto.RegisterMapType((map[string]string)(nil), "api.Resource.PropertiesEntry")
	proto.RegisterType((*Resources)(nil), "api.Resources")
	proto.RegisterType((*ResourcePlan)(nil), "api.ResourcePlan")
	proto.RegisterType((*GetResourceOpts)(nil), "api.GetResourceOpts")
	proto.RegisterType((*GetResourceTypeOpts)(nil), "api.GetResourceTypeOpts")
}

func init() { proto.RegisterFile("resource.proto", fileDescriptor_d1b72f771c35e3b8) }

var fileDescriptor_d1b72f771c35e3b8 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5b, 0x6b, 0x13, 0x41,
	0x14, 0x76, 0x77, 0x73, 0x69, 0x4e, 0xda, 0x24, 0x9d, 0xaa, 0x2c, 0x52, 0x25, 0x0c, 0x04, 0x03,
	0x62, 0x1e, 0x22, 0x48, 0x10, 0x8a, 0x54, 0xba, 0xd4, 0x52, 0x9a, 0x2c, 0x9b, 0xa2, 0xf8, 0xa4,
	0x63, 0x77, 0x8c, 0x43, 0xe2, 0xee, 0x30, 0xb3, 0xad, 0xdd, 0x1f, 0xe0, 0x93, 0x7f, 0x5a, 0x76,
	0x32, 0xb3, 0x3b, 0xab, 0x05, 0xfb, 0x76, 0xe6, 0x5c, 0xbe, 0x73, 0xbe, 0x73, 0x19, 0xe8, 0x09,
	0x2a, 0xd3, 0x6b, 0x71, 0x45, 0x27, 0x5c, 0xa4, 0x59, 0x8a, 0x3c, 0xc2, 0x19, 0xfe, 0x02, 0xbb,
	0xa1, 0x48, 0x6f, 0x58, 0x4c, 0xc5, 0x82, 0x67, 0x12, 0x21, 0x68, 0x64, 0x39, 0xa7, 0xbe, 0x33,
	0x74, 0xc6, 0x9d, 0x48, 0xc9, 0xe8, 0x10, 0x3a, 0x09, 0xf9, 0x41, 0x25, 0x27, 0x57, 0xd4, 0x77,
	0x95, 0xa1, 0x52, 0xa0, 0x67, 0x00, 0x5c, 0x23, 0x9c, 0xc5, 0xbe, 0xa7, 0xcc, 0x96, 0x06, 0xbf,
	0x83, 0xdd, 0x48, 0x27, 0xbe, 0x2c, 0xd0, 0x10, 0x34, 0x8a, 0x60, 0x93, 0xa1, 0x90, 0x15, 0x06,
	0xc9, 0xbe, 0x87, 0x82, 0x7e, 0x63, 0xb7, 0x25, 0x46, 0xa9, 0xc1, 0x33, 0xd8, 0xb3, 0x31, 0x24,
	0x7a, 0x0e, 0xcd, 0xa2, 0x34, 0xe9, 0x3b, 0x43, 0x6f, 0xdc, 0x9d, 0xee, 0x4f, 0x08, 0x67, 0x13,
	0xdb, 0x25, 0xda, 0xda, 0xf1, 0x5b, 0xe8, 0x1a, 0xf5, 0x39, 0xcd, 0x91, 0x0f, 0xed, 0x35, 0xcd,
	0xe7, 0x55, 0x7e, 0xf3, 0x44, 0x8f, 0xa1, 0x25, 0xe8, 0x2a, 0xb8, 0xe5, 0x9a, 0xa1, 0x7e, 0xe1,
	0x5f, 0x1e, 0xec, 0x18, 0x04, 0xd4, 0x03, 0x97, 0xc5, 0x3a, 0xd2, 0x65, 0x71, 0xc1, 0x65, 0xcd,
	0x92, 0x58, 0x87, 0x28, 0xb9, 0xe4, 0xe7, 0x59, 0xfc, 0x5e, 0x43, 0x3b, 0xfd, 0x99, 0x14, 0x75,
	0xf9, 0x8d, 0xa1, 0x33, 0xee, 0x4d, 0x0f, 0x6b, 0x05, 0x97, 0xc2, 0x59, 0xac, 0x6a, 0x37, 0xce,
	0x68, 0x04, 0x0d, 0xbe, 0x21, 0x89, 0xdf, 0x1c, 0x3a, 0xff, 0xb0, 0x0c, 0x37, 0x24, 0x89, 0x94,
	0x59, 0x0d, 0x8d, 0xac, 0xa4, 0xdf, 0x1a, 0x7a, 0x6a, 0x68, 0x64, 0x25, 0xd1, 0x91, 0x1a, 0x0b,
	0xa7, 0x22, 0x63, 0x54, 0xfa, 0x6d, 0xd5, 0xa6, 0xa7, 0xf5, 0xac, 0x61, 0x69, 0x0f, 0x92, 0x4c,
	0xe4, 0x91, 0x15, 0xf0, 0xe4, 0x08, 0xfa, 0x7f, 0x99, 0xd1, 0x00, 0xbc, 0x35, 0xcd, 0x35, 0xfb,
	0x42, 0x44, 0x0f, 0xa1, 0x79, 0x43, 0x36, 0xd7, 0x66, 0x29, 0xb6, 0x8f, 0x37, 0xee, 0xcc, 0xc1,
	0x21, 0xf4, 0xea, 0x9c, 0xd0, 0x01, 0xf4, 0x17, 0xf3, 0x60, 0x19, 0xbe, 0x0f, 0xa2, 0xe0, 0xf3,
	0xe2, 0xe3, 0x3c, 0x38, 0x19, 0x3c, 0x40, 0x8f, 0x60, 0xbf, 0x52, 0x5e, 0x1c, 0xcf, 0x8f, 0x4f,
	0x83, 0x93, 0x81, 0x83, 0x10, 0xf4, 0x96, 0x9f, 0x96, 0x97, 0xc1, 0x45, 0xa9, 0x73, 0xf1, 0x0c,
	0x3a, 0x06, 0x51, 0xa2, 0x17, 0xd0, 0x31, 0xcb, 0x6c, 0x56, 0x60, 0xaf, 0xc6, 0x2d, 0xaa, 0xec,
	0xf6, 0x02, 0x86, 0xba, 0x5b, 0x77, 0x2d, 0x20, 0xe1, 0xec, 0x03, 0x15, 0x92, 0xa5, 0x89, 0xa6,
	0x63, 0x69, 0xf0, 0x6f, 0x07, 0xfa, 0xa7, 0x34, 0x33, 0x38, 0xea, 0x54, 0x70, 0xd5, 0x8f, 0xee,
	0x74, 0x50, 0x4b, 0x7f, 0x4e, 0xf3, 0x6d, 0x87, 0x46, 0xfa, 0x9c, 0xdc, 0x3b, 0x06, 0xa8, 0x46,
	0xbd, 0xbd, 0xb0, 0x97, 0xb0, 0x63, 0x2e, 0x46, 0xed, 0x8d, 0x71, 0xb5, 0x4f, 0x33, 0x2a, 0x5d,
	0xf0, 0x1a, 0x0e, 0xac, 0x62, 0x0a, 0x1c, 0x55, 0xd0, 0xc8, 0xba, 0xdd, 0x7b, 0x26, 0x73, 0xff,
	0x9b, 0xec, 0x6b, 0x4b, 0xfd, 0x16, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x35, 0x53, 0xf1,
	0x31, 0x3f, 0x04, 0x00, 0x00,
}
